// flow-typed signature: 53b2749b2aeb286171a4db15cea12ba5
// flow-typed version: <<STUB>>/@commitlint/prompt-cli_v^7.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/prompt-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/prompt-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/prompt-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/prompt-cli/cli.js' {
  declare module.exports: $Exports<'@commitlint/prompt-cli/cli'>;
}
